sudo: false
language: rust
rust:
  - stable
  - beta

matrix:
  allow_failures:
    - rust: nightly

os:
  - linux
  - osx

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.9
      - g++-4.9
      - gcc-4.9-multilib
      - g++-4.9-multilib
  artifacts:
    paths:
      - "./target/release/game_jolt_game_wrapper"

before_install:
  - rustc -V
  - cargo -V
  - 'if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then export CFLAGS="-I/usr/local/opt/openssl/include $CFLAGS" LDFLAGS="-L/usr/local/opt/openssl/lib $LDFLAGS"; fi'
  - git submodule update --init --recursive
  - git clone https://github.com/creationix/nvm.git ./.nvm
  - source ./.nvm/nvm.sh
  - nvm install stable
  - nvm use stable
  - npm install -g gulp-cli

install:
  - npm i

before_script:
  - cargo test --verbose
  - gulp build

script:
  - npm test

env:
  matrix:
    secure: QFayU8sOm3HN8wF1uyS2dpCMGsILKcZxebhDw5oRBh4z7I4iIG+OEmv7IRSzyq+EgH+uAbfM0cDNcAupsVdlgmJVZkmr+Is2qHBa81ALHz7mMloR86wREii9+mX0919KE6l8k3v5REnObcb3fmgGTMbX3KUKgA42KufE0gsxskXlSc2WWFbiBw2OotaFkRmOTKggPujKZ7u1hUJ/gNENBHTAqpxwOC1uDOlbo8CJNgD+9chMTBv1T60gBQRLlI0Vr+4r94ix/8jCMdhzdQc7MQWkbGe0g69DLG45IQ1S2N3VblMvxt85R2xdLTuHNcBFo5o/bWqIOZkjBqvOmzdntfJMCofR4et04iQV+hja02zb7AJM+kmP7qxEFA6bygePPLxY68vxDPp4zdIQh9o8+fsafHbBFOpLz3hTyjEwnYM2Z+tuGsdaSt1pyPzAK3jud1PsCMcOUdLLwjznwfiof1ogKPrPZ6m+N+JF6kQjOOcseCTs2a97mJ6+7qVwe/W2v+V3w7xoR+8IujnOgSApyiZWw/xnz/A0wMkYR0VqmY9N/Mgyv//LoxTPqRi7Ky0YHcdSkwfA2u2E18AwukoowJPGJXd4LnnYjqnr5yWYTQodRZZcCwqStiFJGkVFOKm3CZwo2es/nBmVzz+69L7uwicsabLfA/UdKUB5luRExiU=
