sudo: false
language: rust
rust:
  - stable
  - beta

matrix:
  allow_failures:
    - rust: nightly

os:
  - linux
  - osx

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.9
      - g++-4.9
      - gcc-4.9-multilib
      - g++-4.9-multilib
  artifacts:
    paths:
      - ./bin/game_jolt_client_wrapper_linux
      - ./bin/game_jolt_client_wrapper_osx

before_install:
  - rustc -V
  - cargo -V
  - git submodule update --init --recursive
  - git clone https://github.com/creationix/nvm.git ./.nvm
  - source ./.nvm/nvm.sh
  - nvm install stable
  - nvm use stable
  - npm install -g gulp tsd

install:
  - npm i
  - tsd rate
  - tsd install

before_script:
  - cargo test --verbose
  - gulp build

script:
  - npm test

env:
  global:
    secure: mdFln4bBv55BZWMu/qfuOTj0pWdeW+qKeXA2CRbbJfqQH63xDJyODVSwvK/dv5apmBS5/7HKYkqlO1/fXOGRRXp9l4AOG93lBD91MfgofKs4kI4sl0Wi/MzxUivZijNcgvkLEzSUJgZnY3PXwMb9la1xmnQFpPp2X6mBmKExQUkzJDU3kTMdFQhPfw7ARPRny6cV0Ch1YrH3AXqnlP1o9u41gR8QW140qsd9rhGfMmzzsPpjQOBfLUUBwopkDUOKZWegKUftXO8Ul/VQ29SAa0rYlijVuceV2JQD51iGQJ8J0AsvrN5CoZCbG0viWL9AT7C8uzjsnH1X9lXfhqsLu6Pi5a+4hSKHmnA1sjxbJDOVx0pB2VgldSo9HXJdbWFbZp5mJjq94PAZ0eoTQicXhpuRxscTkHPY0ury5OlW+OOV8UdJnJw9CYngUWht0CzzX4s9JgYDJwYtuu0JEjbEs0/7DUl72PWi+7Fmj+uosMgii0r0NEdJOXO6RjuzUpIuTszVEzwM2eg3xk4oSixSO2wCK5yL51wCB3sf3KdSjL/Neb0KhUya0+cISvMN57vVFMC6QjCW/bnDR3wCUC5mqz1i46/uMHcDPUH9+ConWsRGSYWiH9Gp+8is9M8lcaiFYxzuqffGdQSKMgwYXQadMyLImHAgr/JXACrVFApL7Gw=
