platform:
  - x86

environment:
  matrix:
  - TARGET: i686-pc-windows-gnu

install:
  - ps: Start-FileDownload "https://static.rust-lang.org/dist/rust-nightly-${env:TARGET}.exe"
  - rust-nightly-%TARGET%.exe /VERYSILENT /NORESTART /DIR="C:\Program Files (x86)\Rust"
  - SET PATH=%PATH%;C:\Program Files (x86)\Rust\bin
  - SET PATH=%PATH%;C:\MinGW\bin
  - rustc -V
  - cargo -V
  - ps: Install-Product node 6.9.0 x86 # We need npm@3 for windows builds
  - npm i -g gulp-cli
  - npm i

build_script:
  - gulp build

test_script:
  - cargo test --verbose
  - npm test

artifacts:
  - path: target\release\game_jolt_game_wrapper.exe
